name = "playjonnycasino-at"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=playjonnycasino.at"
HMAC_KEY = "21717cfb9cf3762e6c958d187469e6d7ebd7bcd6ceade4a966617626270dcf00"
COOKIE_NAME = "xp7"
PLAY_PATH = "start-now"
BUTTON_ID = "p0f54ebe0f448252e21e3203ee56d1edc"
GATE_SALT = "7828e7ebba58d768"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "uuka"
CTA_SELECTOR = ".play-button"
